name: "Debug APK Publisher"
branding:
  icon: "package"
  color: "red"
description: "Build & Release Debug APK on GitHub. Load version number from file."
author: "CarlosCGA"
inputs:
  GITHUB_TOKEN:
    required: true
    description: "Github secret token to allow automated publishing of APK to release."
  REPO_BRANCH:
    required: false
    description: "Github repository branch name."
runs:
  using: "docker"
  image: "Dockerfile"
